first=float(input())
second=int(input())
third=input()
print(format(first,'.2f'))
print(format(first, 'e'), end=' ')
print(format(first, 'E'), end=' ')
print(format(first, '.2%'))
print('{:b}'.format(second), end=' ')
print('{:x}'.format(second))
third=third.strip()
print('{}'.format(third.upper()))
print('{:>20}'.format(third))
print('{:*^20}'.format(third))
print("{} + {} = {}".format(first,second,first+second))